 duplication:
    enabled: false
    config:
      languages:
      - ruby
exclude_patterns:
  - ".rubocop*.yml"
  - "spec/"
  - "node_modules/"
  - "!spec/support/helpers"
  - "config/"
  - "db/"
  - "spec/"
  - "vendor/"
  - "coverage/"
  - "bin/"
  - ".idea/"
  - "Guardfile"
  - "public/packs/js/"